COLOR_SWATCH = {
    "green": "#61BD4F",
    "yellow": "#F2D600",
    "orange": "#FF9F1A",
    "red": "#EB5A46",
    "purple": "#C377E0",
    "blue": "#0079BF",
    "sky": "#00C2E0",
    "lime": "#51E898",
    "pink": "#FF78CB",
    "black": "#344563",
    "green_dark": "#519839",
    "yellow_dark": "#D9B51C",
    "orange_dark": "#CD8313",
    "red_dark": "#B04632",
    "purple_dark": "#89609E",
    "blue_dark": "#055A8C",
    "sky_dark": "#096F8C",
    "lime_dark": "#4BBF6B",
    "pink_dark": "#C9558B",
    "black_dark": "#091E42",
    "green_light": "#B7E2A3",
    "yellow_light": "#F5EA92",
    "orange_light": "#FCD6A1",
    "red_light": "#F5B3AB",
    "purple_light": "#DFC0EB",
    "blue_light": "#8BBDD9",
    "sky_light": "#8ED6E5",
    "lime_light": "#B3F0C6",
    "pink_light": "#F8C4E0",
    "black_light": "#7A869A",
    "(none)": "#DFE1E6",
}

# Official Trello label color names (COLOR_SWATCH keys except UI-only "(none)").
LABEL_COLORS = tuple(name for name in COLOR_SWATCH if name != "(none)")

PALETTE_HUES = [
    "green",
    "yellow",
    "orange",
    "red",
    "purple",
    "blue",
    "sky",
    "lime",
    "pink",
    "black",
]
